# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 05:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('abstract', models.CharField(max_length=250, verbose_name='摘要')),
                ('status', models.CharField(choices=[('D', '草稿'), ('P', '已发布'), ('I', '私密')], default='P', max_length=1, verbose_name='状态')),
                ('order', models.PositiveSmallIntegerField(choices=[(3, '3'), (2, '2'), (1, '1'), (0, '0'), (-1, '-1'), (-2, '-2'), (-3, '-3')], default=0, verbose_name='排序')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=10, verbose_name='标签')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-order', '-create_at'],
            },
        ),
    ]
